name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (needed for rclone dependencies sometimes)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Save Service Account JSON
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Create rclone config
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
[drive]
type = drive
scope = drive
service_account_file = /tmp/sa.json
root_folder_id = 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH
EOF

      - name: Upload file to Google Drive
        run: |
          rclone copy ./spotify.png drive: -P
